meta:
  author: Daniele Andriani
  version: "v5"
  engin: 4.1.0
units:
  kx: cx
  ky: cy
  px: kx+6
  py: ky+6
points:
  key:
    padding: ky+2.5
    spread: kx+2.5
  zones:
    main:
      anchor: 
        shift: [100,-100]
      rows:
        bottom:
          row_net: P09
        home:
          row_net: P08
        top:
          row_net: P07
      columns:
        outer:
          key:
            column_net: P01
        pinky:
          key:
            spread: kx+1
            column_net: P02
        ring:
          key:
            spread: kx+4
            stagger: 14
            column_net: P03
        middle:
          key:
            spread: kx+4
            stagger: 4
            column_net: P04
        index:
          key:
            stagger: -4
            column_net: P05
        inner:
          key:
            spread: kx+1
            stagger: -4
            column_net: P06
    thumb:
      anchor:
        ref: main_middle_bottom
        shift: [0, -cy-1.5]
      rows:
        unique:
          row_net: P10
      columns:
        extended:
          key:
            column_net: P03
        inner:
          key:
            stagger: -4
            column_net: P04
        middle:
          key:
            shift: [8, -5]
            splay: -30
            column_net: P05
        outer:
          key:
            shift: [8, -5]
            column_net: P06
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  choc_sockets:
    - what: rectangle
      where: true
      size: [cx-4.25,cy-3.25]
  board:
    - what: polygon
      asym: both
      operation: stack
      fillet: 2
      points:
        - ref: main_outer_top
          shift: [-px/2, py/2-2]
        - ref: main_ring_top
          shift: [-px/2, py/2 +5]
        - ref: main_middle_top
          shift: [-px/2, py/2 +5]
        - ref: main_middle_top
          shift: [px/2, py/2 +5]
        - ref: main_inner_top
          shift: [px/2 - 8, py/2 +13]
        - ref: main_inner_top
          shift: [px/2 - 8, py/2 +5]
        - ref: main_inner_top
          shift: [px/2 - 3, py/2 +5]
        - ref: main_inner_top
          shift: [px/2 - 3, py/2 +13]
        - ref: main_inner_bottom
          shift: [cx+14+px/2, 2ky+py/2 +18]
        - ref: main_inner_bottom
          shift: [cx+14+px/2, -ky/2]
        - ref: thumb_outer_unique
          shift: [-px/2, py/2 +2]
        - ref: thumb_outer_unique
          shift: [px/2, py/2 +2]
        - ref: thumb_outer_unique
          shift: [px/2, -py/2]
        - ref: thumb_inner_unique
          shift: [kx/2, -py/2-2]
        - ref: main_outer_bottom
          shift: [-px/2, -py/2]
  combo_main:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  main:
    template: kicad8
    outlines: 
      main: 
        outline: board
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: [/^main_.*/, /^thumb_.*/]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
      connector:
        what: trrs
        where:
          ref: main_inner_top
          shift: [42, 20]
        params:
          A: P21
          B: VCC
          C: P20
          D: GND
      diode:
        what: diode
        where: [/^main_.*/, /^thumb_.*/]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [4.5, -5]
      underglow_led:
        what: ceoloide/led_sk6812mini-e
        where:
          ref: main_inner_top
          shift: [40, 0]
          rotate: 90
        params:
          reversible: true
          side: B
          P2: P19
          P4: inner_LED
      underglow_led_2:
        what: ceoloide/led_sk6812mini-e
        where:
          ref: main_inner_top
          shift: [40, -15]
          rotate: 90
        params:
          reversible: true
          side: B
          P2: inner_LED
          P4: P20
      text:
        what: infused-kim/text
        where: 
          ref: thumb_outer_unique
          shift: [0, ky/2+3]
        params:
          text: Just anotter keyboard
      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          ref: main_inner_top
          shift: [23, 5]
        params:
          reversible: true
      screen:
        what: oled
        where:
          ref: main_inner_top
          shift: [17, -20]
          rotate: 90
        params:
          side: "F"
          VCC: VCC
          SDA: P18
          SCL: P19
          GND: GND
      knob:
        what: rotary
        where:
          ref: main_inner_bottom
          shift: [kx+12, 5]
        params:
          from: P15
          to: P14
          A: P06
          B: P05
          C: GND